name: Nightly Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g., nightly-YYYY-MM-DD)"
        required: false
        default: "auto"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"
          cache: "maven"

      - name: Build with Maven
        run: mvn --batch-mode compile assembly:single -Dmaven.test.skip=true

      - name: Generate release date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set release version
        id: release_version
        run: |
          if [ "${{ github.event.inputs.version }}" == "auto" ]; then
            echo "version=nightly-${{ steps.date.outputs.date }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_version.outputs.version }}
          name: Nightly Release ${{ steps.release_version.outputs.version }}
          body: |
            Nightly build generated on ${{ steps.date.outputs.date }}

            This is an automated nightly build of the latest code.
          draft: false
          prerelease: true
          files: |
            target/tabula-*-jar-with-dependencies.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
